### ISSUE TITLE
Percentage doesn't update if player leaves bed

### ISSUE THREAD

**Issue by MDMCK10** [CommanderTvis/bukkit-morpheus#1]
**Description**
The percentage of players sleeping doesn't update if a player leaves the bed, which means if someone goes in a bed multiple times they can skip the night without having to wait for other players

**Steps to Reproduce**
set the percentage to a percentage where it requires multiple players to sleep
and then enter a bed and exit it, and then enter it again

**Expected behavior**
the percentage should be reduced when exiting the bed

**Screenshots**
![image](https://user-images.githubusercontent.com/21245760/47239188-dc7d3f00-d3e4-11e8-91c0-d14c562d0573.png)

**Environment:**
 - Minecraft server version: 1.12.2
 - Minecraft client version: 1.8.9
 - Java version: 1.8.0_181
 - Plugin version: 0.1
 - Bukkit/Spigot version: Paper version git-Paper-1582 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - OS: Linux

plugin list: 
![image](https://user-images.githubusercontent.com/21245760/47239210-f028a580-d3e4-11e8-9ddc-e0e855f7dd02.png)

**Comment by MDMCK10** [comment]
yes

**Comment by MDMCK10** [comment]
alright so i just did a tiny bit of testing right now, and it appears that once the day was skipped successfully, it happens after that.
![image](https://user-images.githubusercontent.com/21245760/47239667-4a763600-d3e6-11e8-9b99-27e1c153fee5.png)

**Comment by CommanderTvis** [comment]
rl confirm terribly works with current configuration code

**Comment by CommanderTvis** [comment]
i'll rewrite it

**Comment by MDMCK10** [comment]
this happened on a fresh restart btw

**Comment by CommanderTvis** [comment]
hm

**Comment by MDMCK10** [comment]
![image](https://user-images.githubusercontent.com/21245760/47239755-7a253e00-d3e6-11e8-891c-a7f48195f7b9.png)
here is a screenshot of it working just fine before that

**Comment by MDMCK10** [comment]
so basically
first sleep: the percentage reducing works fine
sleep after that: it doesn't reduce

**Comment by CommanderTvis** [comment]
thanks for description

**Comment by MDMCK10** [comment]
not much of a java guy myself, but i think i found the issue:
https://github.com/CommanderTvis/Bukkit-Morpheus/blob/master/src/main/kotlin/io/github/commandertvis/morpheus/listeners/MorpheusListener.kt#L38
wasn't that supposed to be set to false the second time?

**Comment by CommanderTvis** [comment]
yep

**Comment by CommanderTvis** [comment]
i'll publish update tomorrow

**Comment by MDMCK10** [comment]
alright, thanks!

**Comment by CommanderTvis** [comment]
Fixed
