### ISSUE TITLE
what

### ISSUE THREAD

**Issue by MDMCK10** [CommanderTvis/bukkit-morpheus#3]
**Description**
i seriously dont know how to describe this, but an image can say more than 1000 words so i attached one of those

**Steps to Reproduce**
sleep

**Expected behavior**
for that to like not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/21245760/47257004-7c3fd900-d488-11e8-9e09-15d0c699ae92.png)

**Environment:**
 - Minecraft server version: 1.12.2
 - Minecraft client version: 1.8.9
 - Java version: 1.8.0_181
 - Plugin version: 0.3
 - Bukkit/Spigot version: git-Paper-1582 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - OS: Linux

**Comment by CommanderTvis** [comment]
@MDMCK10 can you test this .jar
[for-test.zip](https://github.com/CommanderTvis/bukkit-morpheus/files/2498281/for-test.zip)?

**Comment by MDMCK10** [comment]
sorry for the late reply but seems like it works fine now

**Comment by MDMCK10** [comment]
@CommanderTvis the .jar you told me to test works fine

**Comment by CommanderTvis** [comment]
@MDMCK10 thanks for test.
