### ISSUE TITLE
If a player sleeps for long enough, it will be day even if it hasn't reached the percentage yet

### ISSUE THREAD

**Issue by MDMCK10** [CommanderTvis/bukkit-morpheus#5]
**Description**
If a player sleeps for long enough, it will be day even if it hasn't reached the percentage yet

**Steps to Reproduce**
have atleast 3 players on a server
one of the players has to sleep but the others dont

**Expected behavior**
for it to wait until it reaches the percentage

**Screenshots**
![image](https://user-images.githubusercontent.com/21245760/47265011-aabdc280-d521-11e8-869a-7938909d5150.png)

**Environment:**
 - Minecraft server version: 1.12.2
 - Minecraft client version: 1.8.9
 - Java version: 1.8.0_181
 - Plugin version: the version you sent me to test for #3
 - Bukkit/Spigot version: Paper version git-Paper-1582 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
 - OS: Linux

**Comment by CommanderTvis** [comment]
If there wasn't a message like "good morning" &mdash; it couldn't be my plugin

**Comment by MDMCK10** [comment]
i can't seem to reproduce this again, so i think it's just something that happened once for some reason
